spring:
  datasource:
    url: jdbc:postgresql://ken-oudjani-silva:5532/hotfix1_current
    jdbc-url: ${spring.datasource.url} # used for support
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
